version: "2"

services:
  jupyter:
    container_name: jupyter
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks/:/home/jovyan/work/"
      - "./.locale/:/home/jovyan/.local/"
      - "./.jupyter/:/home/jovyan/.jupyter/"
    command: start-notebook.sh --NotebookApp.token=''
