version: "2"

services:
  jupyter:
    container_name: jupyter
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks/:/home/jovyan/work/"
      - "./notebooks/kaggle/corpora/stopwords/:/home/jovyan/nltk_data/corpora/stopwords"
      - "./.local/:/home/jovyan/.local/"
      - "./.jupyter/:/home/jovyan/.jupyter/"
      - "./.ipython/:/home/jovyan/.python/"
    command: start-notebook.sh --NotebookApp.token=''
